// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyviylbwybzjcnetquus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5dml5bGJ3eWJ6amNuZXRxdXVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NTg2MzUsImV4cCI6MjA2MjAzNDYzNX0.1MEuLI-4ZhQokzppjybWvozkpTbqD7_SR3bQ3eWiTTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);